'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const core=require('./core.cjs'),{createProvider}=require('./vocab-provider.cjs'),{createPolicy,readJSON:read}=require('./hosting.cjs');
const ANALYTICS_URL='https://englishfornoar.co.il/api/analytics';
function report(event){const allowed=/^rivals_(room_created|spectator_joined|player_joined|match_started|match_completed|bank|raise|band2_correct|band2_incorrect|band3_correct|band3_incorrect)$/;if(!allowed.test(event))return;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),2500);fetch(ANALYTICS_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({site:'word-rivals',event,path:'/battle-room',pageKind:'game'}),signal:controller.signal}).catch(()=>{}).finally(()=>clearTimeout(timer));}
const IDLE_MS=30*60*1000,MAX_MS=2*60*60*1000,MAX_PLAYERS=6,ALPHABET='0123456789';
function roomCode(rooms){let code;do{code='';for(let i=0;i<5;i++)code+=ALPHABET[crypto.randomInt(ALPHABET.length)];}while(rooms.has(code));return code;}
function makeServer(options={}){const policy=createPolicy(options),rooms=new Map(),idleMs=options.idleMs||IDLE_MS,maxMs=options.maxMs||MAX_MS,vocab=options.vocabProvider||createProvider({fetchImpl:options.fetchImpl||globalThis.fetch});const token=()=>crypto.randomBytes(24).toString('base64url'),seed=()=>crypto.randomBytes(4).readUInt32BE();
function send(s,m){if(!s.destroyed&&!s.writableEnded)try{s.write(m)}catch{}}function people(r){return[...r.players,...r.spectators]}function clean(){const now=Date.now();for(const[code,r]of rooms)if(now-r.touched>idleMs||now-r.created>maxMs){rooms.delete(code);for(const p of people(r))for(const s of p.streams){send(s,'event: expired\ndata: {}\n\n');s.end()}}}const cleanup=setInterval(clean,60000);cleanup.unref();
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(s=>s.trim().split('=')));function identity(req,r){const t=cookies(req)['wr_'+r.code],pi=r.players.findIndex(p=>p.token===t);if(pi>=0)return{role:'player',index:pi,person:r.players[pi]};const si=r.spectators.findIndex(p=>p.token===t);if(si>=0)return{role:'spectator',index:si,person:r.spectators[si]};return null}
function snapshot(r,id){const role=id?.role||'spectator',you=role==='player'?id.index:null;return{revision:r.revision,code:r.code,role,you,status:r.status,matchId:r.matchId,online:r.players.map(p=>p.streams.size>0),players:r.players.length,maxPlayers:MAX_PLAYERS,spectators:r.spectators.length,requested:role==='spectator'&&!!id?.person?.requested,requests:role==='player'&&you===0?r.spectators.filter(x=>x.requested).map(x=>x.token):[],testMode:!!r.testMode,bots:r.players.map(x=>!!x.bot),game:r.game?core.publicState(r.game):null,expiresAt:Math.min(r.created+maxMs,r.touched+idleMs)}}
function broadcast(r){r.revision++;for(const p of people(r)){const id=identity({headers:{cookie:'wr_'+r.code+'='+p.token}},r),msg='data: '+JSON.stringify(snapshot(r,id))+'\n\n';for(const s of p.streams)send(s,msg)}}function json(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body))}function cookie(res,r,p,req){res.setHeader('Set-Cookie','wr_'+r.code+'='+p.token+'; HttpOnly; SameSite=Strict; Path=/; Max-Age=7200'+(policy.production||req.socket.encrypted?'; Secure':''))}
function scheduleBot(r){if(r.botTimer||r.status!=='playing'||!r.game)return;const p=r.players[r.game.active];if(!p||!p.bot)return;r.botTimer=setTimeout(()=>{r.botTimer=null;if(r.status!=='playing'||!r.game||!r.players[r.game.active]?.bot)return;try{const g=r.game;if(g.step==='decision'){core.apply(g,g.active,{type:'bank',version:g.version});report('rivals_bank')}else{const band=g.step;core.apply(g,g.active,{type:'answer',choiceId:g.question.correctId,version:g.version});report('rivals_'+band+'_correct')}if(g.phase==='over')report('rivals_match_completed');r.touched=Date.now();broadcast(r);scheduleBot(r)}catch{}},900)}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','microphone=(), camera=(), geolocation=()');try{if(!policy.guard(req,res))return;clean();const u=new URL(req.url,'http://local');
if(req.method==='GET'&&['/','/index.html','/demo.html'].includes(u.pathname)){const file=path.join(__dirname,u.pathname==='/demo.html'?'demo.html':'online.html');if(!fs.existsSync(file))return json(res,404,{error:'Build required'});res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return fs.createReadStream(file).pipe(res)}
if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,version:'1.2.0',mode:'battle-room',roomCodeDigits:5,bands:['band2','band3']});
if(req.method==='POST'&&u.pathname==='/api/create'){const body=await read(req),datasets=await vocab.loadGame(),p={token:token(),streams:new Set(),last:0,requested:false},now=Date.now(),code=roomCode(rooms),r={code,revision:0,players:[p],spectators:[],testMode:body.testMode===true,created:now,touched:now,status:'lobby',matchId:null,game:null,datasets};rooms.set(code,r);report('rivals_room_created');cookie(res,r,p,req);return json(res,201,snapshot(r,{role:'player',index:0,person:p}))}
if(req.method==='POST'&&u.pathname==='/api/join'){const body=await read(req),code=String(body.code||'').trim();if(!/^\d{5}$/.test(code))return json(res,400,{error:'Use a 5-digit room code'});const r=rooms.get(code);if(!r)return json(res,404,{error:'Room not found or expired'});let id=identity(req,r);if(id)return json(res,200,snapshot(r,id));const p={token:token(),streams:new Set(),last:0,requested:false};r.spectators.push(p);report('rivals_spectator_joined');r.touched=Date.now();cookie(res,r,p,req);broadcast(r);return json(res,200,snapshot(r,{role:'spectator',index:r.spectators.length-1,person:p}))}
const code=String(u.searchParams.get('room')||''),r=rooms.get(code);if(!r)return json(res,404,{error:'Room not found or expired'});const id=identity(req,r);if(!id)return json(res,403,{error:'Join this room first'});
if(req.method==='GET'&&u.pathname==='/api/state')return json(res,200,snapshot(r,id));
if(req.method==='GET'&&u.pathname==='/events'){const p=id.person;res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write('retry: 1500\n\n');p.streams.add(res);broadcast(r);const beat=setInterval(()=>send(res,': ping\n\n'),15000);beat.unref();req.on('close',()=>{clearInterval(beat);p.streams.delete(res);broadcast(r)});return}
if(req.method==='POST'&&u.pathname==='/api/action'){const a=await read(req),now=Date.now(),p=id.person;if(now-p.last<80)return json(res,429,{error:'Please wait a moment'});p.last=now;
if(a.type==='addBot'){if(!r.testMode||id.role!=='player'||id.index!==0||r.status!=='lobby')return json(res,403,{error:'Test bot unavailable'});if(r.players.length>=MAX_PLAYERS)return json(res,409,{error:'This room is full'});r.players.push({token:'virtual-'+token(),streams:new Set(),last:0,requested:false,bot:true});report('rivals_player_joined');}
else if(a.type==='requestPlayer'){if(id.role!=='spectator')return json(res,409,{error:'Already a player'});if(r.status!=='lobby')return json(res,409,{error:'אפשר להצטרף כשחקן במשחק הבא'});if(r.players.length>=MAX_PLAYERS)return json(res,409,{error:'This room is full'});p.requested=true}
else if(a.type==='approve'||a.type==='reject'){if(id.role!=='player'||id.index!==0||r.status!=='lobby')return json(res,403,{error:'Only Player 1 can manage requests before the game'});const si=r.spectators.findIndex(x=>x.token===a.requestToken&&x.requested);if(si<0)return json(res,404,{error:'Request not found'});const sp=r.spectators[si];if(a.type==='approve'){if(r.players.length>=MAX_PLAYERS)return json(res,409,{error:'This room is full'});r.spectators.splice(si,1);sp.requested=false;r.players.push(sp);report('rivals_player_joined')}else sp.requested=false}
else if(a.type==='start'){if(id.role!=='player'||id.index!==0||r.status!=='lobby'||r.players.length<2)return json(res,409,{error:'Player 1 can start when at least two players have joined'});r.game=core.createGame(r.datasets,seed(),r.players.length,0);r.matchId=token();r.status='playing';report('rivals_match_started');for(const sp of r.spectators)sp.requested=false}
else{if(id.role!=='player')return json(res,403,{error:'Spectators cannot answer'});if(r.status!=='playing'||!r.game)throw new Error('The game has not started');if(a.matchId!==r.matchId)return json(res,409,{error:'Stale match'});const band=r.game.step;const wasOver=r.game.phase==='over';core.apply(r.game,id.index,a);if(a.type==='bank'||a.type==='raise')report('rivals_'+a.type);else if(a.type==='answer'&&(band==='band2'||band==='band3'))report('rivals_'+band+'_'+(r.game.feedback?.ok?'correct':'incorrect'));if(!wasOver&&r.game.phase==='over')report('rivals_match_completed')}
r.touched=now;broadcast(r);if(r.status==='playing')scheduleBot(r);return json(res,200,snapshot(r,identity(req,r)||id))}
return json(res,404,{error:'Not found'})}catch(e){if(!res.destroyed&&!res.writableEnded)return json(res,e.status||400,{error:e instanceof SyntaxError?'Invalid JSON':e.message})}});
server.requestTimeout=15000;server.headersTimeout=10000;server.on('close',()=>{clearInterval(cleanup);for(const r of rooms.values())for(const p of people(r))for(const s of p.streams)s.end();rooms.clear()});return{server,rooms,clean,vocab}}
if(require.main===module){const port=Number(process.env.PORT||8787);makeServer().server.listen(port,process.env.HOST||'127.0.0.1',()=>console.log('Battle Room engine ready'))}module.exports={makeServer,roomCode,MAX_PLAYERS};
